# Generated by Django 3.2 on 2023-06-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fass_web_server', '0002_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, default='deforestation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, default='Not Resolved', max_length=255),
        ),
    ]
