# Generated by Django 3.2 on 2023-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fass_web_server', '0003_auto_20230629_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sound_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
